packages:
  - .
  - 'packages/*'
overrides:
  webpack: 5.90.0
allowBuilds:
  '@swc/core': true
  '@tarojs/binding': true
  core-js: true
  core-js-pure: true
  esbuild: true
  sharp: true
  swiper: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
